# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Car.destroy_all
Model.destroy_all
Make.destroy_all
User.destroy_all

@admin = User.create!(username: 'admin', email: 'shammaq@gmail.com', password: '1234567')

puts "#{User.count} users created"

@acura = Make.create!(name: 'Acura')
@alfa_romeo = Make.create!(name: 'Alfa-Romeo')
@aston_martin = Make.create!(name: 'Aston-martin')
@audi = Make.create!(name: 'Audi')
@bentley = Make.create!(name: 'Bentley')
@bmw = Make.create!(name: 'Bmw')
@bugatti = Make.create!(name: 'Bugatti')
@buick = Make.create!(name: 'Buick')
@cadillac = Make.create!(name: 'Cadillac')
@chevrolet = Make.create!(name: 'Chevrolet')
@chrysler = Make.create!(name: 'Chrysler')
@citroen = Make.create!(name: 'Citroen')
@dodge = Make.create!(name: 'Dodge')
@ferrari = Make.create!(name: 'Ferrari')
@fiat = Make.create!(name: 'Fiat')
@ford = Make.create!(name: 'Ford')
@geely = Make.create!(name: 'Geely')
@genesis = Make.create!(name: 'Genesis')
@gm = Make.create!(name: 'GM')
@gmc = Make.create!(name: 'GMC')
@honda = Make.create!(name: 'Honda')
@hyundai = Make.create!(name: 'Hyundai')
@infiniti = Make.create!(name: 'Infiniti')
@jaguar = Make.create!(name: 'Jaguar')
@jeep = Make.create!(name: 'Jeep')
@kia = Make.create!(name: 'Kia')
@koenigsegg = Make.create!(name: 'Koenigsegg')
@lamborghini = Make.create!(name: 'Lamborghini')
@lancia = Make.create!(name: 'Lancia')
@land_rover = Make.create!(name: 'Land Rover')
@lexus = Make.create!(name: 'Lexus')
@lincoln = Make.create!(name: 'Lincoln')
@lotus = Make.create!(name: 'Lotus')
@maserati = Make.create!(name: 'Maserati')
@maybach = Make.create!(name: 'Maybach')
@mazda = Make.create!(name: 'Mazda')
@mclaren = Make.create!(name: 'Mclaren')
@mercedes = Make.create!(name: 'Mercedes')
@mini = Make.create!(name: 'Mini')
@mitsubishi = Make.create!(name: 'Mitsubishi')
@nissan = Make.create!(name: 'Nissan')
@opel = Make.create!(name: 'Opel')
@pagani = Make.create!(name: 'Pagani')
@peugeot = Make.create!(name: 'Peugeot')
@pontiac = Make.create!(name: 'Pontiac')
@porsche = Make.create!(name: 'Porsche')
@ram = Make.create!(name: 'Ram')
@renault = Make.create!(name: 'Renault')
@rolls_royce = Make.create!(name: 'Rolls-Royce')
@skoda = Make.create!(name:'Skoda')
@smart = Make.create!(name:'Smart')
@subaru = Make.create!(name:'Subaru')
@suzuki = Make.create!(name:'Suziki')
@tesla = Make.create!(name:'Tesla')
@toyota = Make.create!(name:'Toyota')
@volkswagen = Make.create!(name:'Volkswagen')
@volvo = Make.create!(name:'Volvo')

puts "#{Make.count} makes created"

@acura_ixl = Model.create!(name: 'IXL', make: @acura)
@acura_mdx = Model.create!(name: 'MDX', make: @acura)
@acura_nsx = Model.create!(name: 'NSX', make: @acura)
@acura_rdx = Model.create!(name: 'RDX', make: @acura)
@acura_rlx = Model.create!(name: 'RLX', make: @acura)
@acura_tlx = Model.create!(name: 'TLX', make: @acura)
@acura_integra = Model.create!(name: 'Integra', make: @acura)
@acura_rl = Model.create!(name: 'RL', make: @acura)
@acura_tl = Model.create!(name: 'TL', make: @acura)
@acura_tsx = Model.create!(name: 'TSX', make: @acura)
@ar_33_stradale = Model.create!(name: '33 Stradale', make: @alfa_romeo)
@ar_8c = Model.create!(name: '8C', make: @alfa_romeo)
@ar_giulia = Model.create!(name: 'Giulia', make: @alfa_romeo)
@ar_stelvio = Model.create!(name: 'Stelvio', make: @alfa_romeo)
@ar_147 = Model.create!(name: '147', make: @alfa_romeo)
@ar_149 = Model.create!(name: '149', make: @alfa_romeo)
@ar_159 = Model.create!(name: '159', make: @alfa_romeo)
@ar_4c = Model.create!(name: '4C', make: @alfa_romeo)
@ar_brera = Model.create!(name: 'Brera', make: @alfa_romeo)
@ar_giulietta = Model.create!(name: 'Giulietta', make: @alfa_romeo)
@ar_gt = Model.create!(name: 'GT', make: @alfa_romeo)
@ar_milano = Model.create!(name: 'Milano', make: @alfa_romeo)
@ar_mito = Model.create!(name: 'MiTo', make: @alfa_romeo)
@ar_spider = Model.create!(name: 'Spider', make: @alfa_romeo)
@am_dbx = Model.create!(name: 'DBX', make: @aston_martin)
@am_vantage = Model.create!(name: 'Vantage', make: @aston_martin)
@am_roadster = Model.create!(name: 'Roadster', make: @aston_martin)
@am_amr = Model.create!(name: 'AMR', make: @aston_martin)
@am_db11 = Model.create!(name: 'DB11', make: @aston_martin)
@am_dbs_superleggera = Model.create!(name: 'DBS Superleggera', make: @aston_martin)
@am_dbs_superleggera_volante = Model.create!(name: 'DBS Superleggera Volante', make: @aston_martin)
@am_valkyrie = Model.create!(name: 'Valkyrie', make: @aston_martin)
@am_valhalla = Model.create!(name: 'Valhalla', make: @aston_martin)
@am_speedster = Model.create!(name: 'Speedster', make: @aston_martin)
@audi_a5 = Model.create!(name: 'A5', make: @audi)
@audi_s5 = Model.create!(name: 'S5', make: @audi)
@audi_q7 = Model.create!(name: 'Q7', make: @audi)
@audi_a7 = Model.create!(name: 'A7', make: @audi)
@audi_a8 = Model.create!(name: 'A8', make: @audi)
@audi_q5 = Model.create!(name: 'Q5', make: @audi)
@audi_a4 = Model.create!(name: 'A4', make: @audi)
@audi_r8 = Model.create!(name: 'R8', make: @audi)
@audi_q8 = Model.create!(name: 'Q8', make: @audi)
@audi_etron = Model.create!(name: 'Etron', make: @audi)
@audi_rs6 = Model.create!(name: 'RS6', make: @audi)
@bentley_hunaudieres = Model.create!(name: 'Hunaudières', make: @bentley)




puts "#{Model.count} models created"

@car1 = Car.create!(user: @admin, img_url: 'https://media.ed.edmunds-media.com/acura/mdx/2020/oem/2020_acura_mdx_4dr-suv_sh-awd-pmc-edition_fq_oem_1_1600.jpg', make:'Acura', model: @acura_mdx, color: 'red', year: 2022, mileage: 0, price: 46900, description:'The redesigned 2022 MDX houses a 290-HP81 V-6 engine paired to a new double-wishbone front suspension for precision cornering. Handling is further enhanced by the Integrated Dynamics System and available wider 20-in alloy wheels for adrenaline-inducing performance. Be ready for most any drive with available Super Handling All-Wheel Drive™ (SH-AWD®) and a max towing capacity of up to 5,000 lbs.99')
@car2 = Car.create!(user: @admin, img_url: 'https://www.fullertonalfaromeo.com/inventoryphotos/4746/zarfanan3m7643217/ip/3.jpg?width=2000', make:'Alfa Romeo', model: @ar_giulia, color: 'black', year: 2021, mileage: 0, price: 43690, description:'The 2020 Giulia is available in three main trim levels: the base Giulia, the Ti and the high-performance Quadrifoglio. The Giulia and Ti models are powered by a turbocharged 2.0-liter four-cylinder engine (280 horsepower, 306 lb-ft) that puts its power to the rear wheels through an eight-speed automatic transmission. All-wheel drive is also available for all 2.0-liter cars. The Quadrifoglio uses a turbocharged 2.9-liter V6 engine (505 hp, 443 lb-ft).')

puts "#{Car.count} cars created"